import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JScrollPane;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.ScrollPaneConstants;

import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import javax.swing.JLabel;

public class GUI extends javax.swing.JFrame {
	// Communicator object
	Communicator communicator = null;
	// KeybindingController object
	KeybindingController keybindingController = null;

	/** Creates new form GUI */
	public GUI() {
		initComponents();
		createObjects();
		communicator.searchForPorts();
		keybindingController.toggleControls();
		keybindingController.bindKeys();
	}

	private void createObjects() {
		communicator = new Communicator(this);
		keybindingController = new KeybindingController(this);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("18F458 Control Panel");
		GridBagLayout gridBagLayout = new GridBagLayout();
		gridBagLayout.columnWidths = new int[] { 69, 95, 112, 34, 90, 220, 0 };
		gridBagLayout.rowHeights = new int[] { 17, 14, 25, 25, 15, 25, 22, 25, 14, 0 };
		gridBagLayout.columnWeights = new double[] { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE };
		gridBagLayout.rowWeights = new double[] { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE };
		getContentPane().setLayout(gridBagLayout);

		jLabel1 = new javax.swing.JLabel();
		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
		jLabel1.setText("18F458 Control Panel");
		GridBagConstraints gbc_jLabel1 = new GridBagConstraints();
		gbc_jLabel1.anchor = GridBagConstraints.NORTHWEST;
		gbc_jLabel1.insets = new Insets(0, 0, 5, 5);
		gbc_jLabel1.gridwidth = 2;
		gbc_jLabel1.gridx = 0;
		gbc_jLabel1.gridy = 0;
		getContentPane().add(jLabel1, gbc_jLabel1);

		jLabel5 = new javax.swing.JLabel();
		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
		jLabel5.setText("Select the COM Port");
		GridBagConstraints gbc_jLabel5 = new GridBagConstraints();
		gbc_jLabel5.anchor = GridBagConstraints.NORTHWEST;
		gbc_jLabel5.insets = new Insets(0, 0, 5, 5);
		gbc_jLabel5.gridwidth = 2;
		gbc_jLabel5.gridx = 0;
		gbc_jLabel5.gridy = 1;
		getContentPane().add(jLabel5, gbc_jLabel5);

		jLabel13 = new javax.swing.JLabel();
		jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11));
		jLabel13.setText("Log");
		GridBagConstraints gbc_jLabel13 = new GridBagConstraints();
		gbc_jLabel13.anchor = GridBagConstraints.NORTHEAST;
		gbc_jLabel13.insets = new Insets(0, 0, 5, 5);
		gbc_jLabel13.gridx = 3;
		gbc_jLabel13.gridy = 1;
		getContentPane().add(jLabel13, gbc_jLabel13);

		txtLog = new javax.swing.JTextArea();
		txtLog.setColumns(20);
		txtLog.setEditable(false);
		txtLog.setLineWrap(true);
		txtLog.setRows(5);
		txtLog.setFocusable(false);
		GridBagConstraints gbc_txtLog = new GridBagConstraints();
		gbc_txtLog.anchor = GridBagConstraints.BASELINE_LEADING;
		gbc_txtLog.insets = new Insets(0, 0, 5, 0);
		gbc_txtLog.gridx = 5;
		gbc_txtLog.gridy = 2;
		

		JScrollPane scroll = new JScrollPane(txtLog);
		scroll.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
		getContentPane().add(scroll, gbc_txtLog);
		

		cboxPorts = new javax.swing.JComboBox();
		GridBagConstraints gbc_cboxPorts = new GridBagConstraints();
		gbc_cboxPorts.anchor = GridBagConstraints.NORTH;
		gbc_cboxPorts.fill = GridBagConstraints.HORIZONTAL;
		gbc_cboxPorts.insets = new Insets(0, 0, 5, 5);
		gbc_cboxPorts.gridx = 0;
		gbc_cboxPorts.gridy = 3;
		getContentPane().add(cboxPorts, gbc_cboxPorts);

		btnDisconnect = new javax.swing.JButton();
		btnDisconnect.setText("Disconnect");
		btnDisconnect.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDisconnectActionPerformed(evt);
			}
		});
		GridBagConstraints gbc_btnDisconnect = new GridBagConstraints();
		gbc_btnDisconnect.anchor = GridBagConstraints.NORTHWEST;
		gbc_btnDisconnect.insets = new Insets(0, 0, 5, 5);
		gbc_btnDisconnect.gridx = 2;
		gbc_btnDisconnect.gridy = 3;
		getContentPane().add(btnDisconnect, gbc_btnDisconnect);

		btnConnect = new javax.swing.JButton();
		btnConnect.setText("Connect");
		btnConnect.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtLog.setText("");
				btnConnectActionPerformed(evt);	
			}
		});
		GridBagConstraints gbc_btnConnect = new GridBagConstraints();
		gbc_btnConnect.anchor = GridBagConstraints.NORTHWEST;
		gbc_btnConnect.insets = new Insets(0, 0, 5, 5);
		gbc_btnConnect.gridx = 1;
		gbc_btnConnect.gridy = 3;
		getContentPane().add(btnConnect, gbc_btnConnect);

		jLabel3 = new javax.swing.JLabel();
		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel3.setText("Limit");
		GridBagConstraints gbc_jLabel3 = new GridBagConstraints();
		gbc_jLabel3.anchor = GridBagConstraints.NORTHWEST;
		gbc_jLabel3.insets = new Insets(0, 0, 5, 5);
		gbc_jLabel3.gridx = 0;
		gbc_jLabel3.gridy = 4;
		getContentPane().add(jLabel3, gbc_jLabel3);

		btnFurther = new javax.swing.JButton();
		btnFurther.setText("/\\");
		btnFurther.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnLeftAccelActionPerformed(evt);
			}
		});
		GridBagConstraints gbc_btnFurther = new GridBagConstraints();
		gbc_btnFurther.fill = GridBagConstraints.BOTH;
		gbc_btnFurther.insets = new Insets(0, 0, 5, 5);
		gbc_btnFurther.gridx = 1;
		gbc_btnFurther.gridy = 5;
		getContentPane().add(btnFurther, gbc_btnFurther);
		
		lblLimitRespected = new JLabel("Limit Respected");
		lblLimitRespected.setBackground(Color.GREEN);
		lblLimitRespected.setForeground(Color.GREEN);
		GridBagConstraints gbc_lblLimitRespected = new GridBagConstraints();
		gbc_lblLimitRespected.insets = new Insets(0, 0, 5, 0);
		gbc_lblLimitRespected.gridx = 5;
		gbc_lblLimitRespected.gridy = 5;
		getContentPane().add(lblLimitRespected, gbc_lblLimitRespected);

		lblLimit = new javax.swing.JLabel();
		lblLimit.setFont(new java.awt.Font("Tahoma", 1, 18));
		lblLimit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lblLimit.setText("400");
		GridBagConstraints gbc_lblLimit = new GridBagConstraints();
		gbc_lblLimit.anchor = GridBagConstraints.NORTH;
		gbc_lblLimit.fill = GridBagConstraints.HORIZONTAL;
		gbc_lblLimit.insets = new Insets(0, 0, 5, 5);
		gbc_lblLimit.gridx = 1;
		gbc_lblLimit.gridy = 6;
		getContentPane().add(lblLimit, gbc_lblLimit);
		
		btnCloser = new javax.swing.JButton();
		btnCloser.setText("\\/");
		btnCloser.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnLeftDecelActionPerformed(evt);
			}
		});
		GridBagConstraints gbc_btnCloser = new GridBagConstraints();
		gbc_btnCloser.fill = GridBagConstraints.HORIZONTAL;
		gbc_btnCloser.anchor = GridBagConstraints.NORTH;
		gbc_btnCloser.insets = new Insets(0, 0, 5, 5);
		gbc_btnCloser.gridx = 1;
		gbc_btnCloser.gridy = 7;
		getContentPane().add(btnCloser, gbc_btnCloser);

		jLabel6 = new javax.swing.JLabel();
		jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
		jLabel6.setText("Controls");
		GridBagConstraints gbc_jLabel6 = new GridBagConstraints();
		gbc_jLabel6.anchor = GridBagConstraints.NORTHWEST;
		gbc_jLabel6.insets = new Insets(0, 0, 0, 5);
		gbc_jLabel6.gridx = 0;
		gbc_jLabel6.gridy = 8;
		getContentPane().add(jLabel6, gbc_jLabel6);

		pack();
	}

	private void btnLeftAccelActionPerformed(java.awt.event.ActionEvent evt) {
		keybindingController.setLimit(keybindingController.further(keybindingController.getLimit()));
		keybindingController.updateLabels();
	}

	private void btnLeftDecelActionPerformed(java.awt.event.ActionEvent evt) {
		keybindingController.setLimit(keybindingController.closer(keybindingController.getLimit()));
		keybindingController.updateLabels();
	}

	private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {
		communicator.connect();
		if (communicator.getConnected() == true) {
			if (communicator.initIOStream() == true) {
				communicator.initListener();
			}
		}
	}

	private void btnDisconnectActionPerformed(java.awt.event.ActionEvent evt) {
		communicator.disconnect();
	}

	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GUI().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	public javax.swing.JButton btnConnect;
	public javax.swing.JButton btnDisconnect;
	public javax.swing.JButton btnFurther;
	public javax.swing.JButton btnCloser;
	public javax.swing.JComboBox cboxPorts;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	public javax.swing.JLabel lblLimit;
	public javax.swing.JTextArea txtLog;
	JLabel lblLimitRespected;
}
