language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
 
matrix:
    allow_failures:
        - php: hhvm
 
before_script:
    - composer self-update
    - composer install
 
script:
    - script: phpunit --configuration phpunit.xml
    - phpunit test GeorgesWebsite/INC/test.php
 
notifications:
    email: false
